apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomato
  labels:
    app: zomato
spec:
  replicas: 5
  selector:
    matchLabels:
      app: zomato
  template:
    metadata:
      labels:
        app: zomato
   spec:
   containers:
   - name: mydockerprojectfor5pm
     image: sueesh144/steakhouse:latest
     command: ["/bin/sh", "-c"]
     args: ["python manage.py migrate && gunicorn --bind 0.0.0.0:8000 restaurant.wsgi:application"]
     ports:
     - containerPort: 8000
