apiVersion: v1
kind: Service
metadata:
  name: zomato-svc
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
  - protocol: TCP
    port: 3000          # Service port
    targetPort: 3000  # Container port

