apiVersion: v1
kind: Service
metadata:
  name: zomato-svc
spec:
  type: LoadBalancer
  selector:
    app: zomato
  ports:
  - protocol: TCP
    port: 80          # Updated from 3000
    targetPort: 80    # Updated from 3000

